spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastrax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: <db-id>
  region: asia-south1
  keyspace:
  application.token: <db-token>